import type { Metadata } from "next";
import { Orbitron, Archivo } from "next/font/google";
import "./globals.css";
import { RoadmapProvider } from "./context/RoadmapContext";
import ProgressNavbar from "./components/ProgressNavbar";
import ConditionalPadding from "./components/ConditionalPadding";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${archivo.variable} antialiased`}
      >
        <RoadmapProvider>
          <ConditionalPadding>
            <ProgressNavbar />
            {children}
          </ConditionalPadding>
        </RoadmapProvider>
      </body>
    </html>
  );
}
