import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { RoadmapProvider } from "./context/RoadmapContext";
import ProgressNavbar from "./components/ProgressNavbar";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        <RoadmapProvider>
          <ProgressNavbar />
          {children}
        </RoadmapProvider>
      </body>
    </html>
  );
}
